-- PostgreSQL schema for Toshio Restaurant. Run with Supabase SQL Editor.
create table if not exists stores (
  id text primary key, name text not null, tagline text not null default '',
  announcement text not null default '', is_open boolean not null default true,
  address text not null default '', phone text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists categories (
  id bigint generated by default as identity primary key,
  store_id text not null references stores(id) on delete cascade,
  name text not null, sort_order integer not null default 0,
  unique (store_id, name), unique (id, store_id)
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  store_id text not null references stores(id) on delete cascade,
  name text not null, description text not null default '', price integer not null check (price >= 0),
  category_id bigint, image text not null default '', status text not null check (status in ('active','inactive')),
  sort_order integer not null default 0, created_at timestamptz not null default now(),
  foreign key (category_id, store_id) references categories(id, store_id) on delete restrict
);
create index if not exists products_store_sort_idx on products(store_id, sort_order);

create table if not exists orders (
  id text primary key, store_id text not null references stores(id) on delete restrict,
  table_no text not null, total integer not null check (total >= 0),
  status text not null check (status in ('new','preparing','completed','cancelled')),
  created_at timestamptz not null default now()
);
create index if not exists orders_store_created_idx on orders(store_id, created_at desc);

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id text not null references orders(id) on delete cascade,
  product_id bigint references products(id) on delete set null,
  product_name text not null, unit_price integer not null check (unit_price >= 0),
  quantity integer not null check (quantity between 1 and 99),
  subtotal integer not null check (subtotal = unit_price * quantity)
);

-- Public guests may read only active menu items through the API. Keep direct
-- table access private: service-role credentials belong only on the backend.
alter table stores enable row level security;
alter table categories enable row level security;
alter table products enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;
