import 'dotenv/config';
import express, { Request, Response, NextFunction } from 'express';
import cors from 'cors';
import multer from 'multer';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { PostgresRepository } from './postgres-repository.js';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { rateLimit } from 'express-rate-limit';
import { randomUUID } from 'node:crypto';

const here=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(here,'../..');
const dataDir=path.join(root,'data');
const productsFile=path.join(dataDir,'products.json');
const ordersFile=path.join(dataDir,'orders.json');
const storeFile=path.join(dataDir,'store.json');
const storesFile=path.join(dataDir,'stores.json');
type Store={id:string;name:string;tagline:string;announcement:string;isOpen:boolean;address:string;phone:string};
type Product={id:number;storeId:string;name:string;description:string;price:number;category:string;image:string;status:'active'|'inactive';sortOrder:number};
type OrderItem={productId:number;name:string;price:number;quantity:number;subtotal:number};
type Order={id:string;storeId:string;tableNo:string;items:OrderItem[];total:number;status:'new'|'preparing'|'completed'|'cancelled';createdAt:string};
type RequestWithCookies=Request & {cookies?:Record<string,string>};
class ApiError extends Error{constructor(public status:number,message:string){super(message)}}
async function ensure(file:string,fallback:unknown){await fs.mkdir(path.dirname(file),{recursive:true});try{await fs.access(file)}catch{await fs.writeFile(file,JSON.stringify(fallback,null,2),'utf8')}}
async function read<T>(file:string):Promise<T>{try{return JSON.parse(await fs.readFile(file,'utf8')) as T}catch{throw new ApiError(500,`数据文件读取失败：${path.basename(file)}`)}}
async function write<T>(file:string,data:T){try{await fs.writeFile(file,JSON.stringify(data,null,2),'utf8')}catch(error){console.error('JSON write failed:',file,error);throw new ApiError(500,'数据文件写入失败')}}
class JsonRepository<T>{constructor(private file:string){} all():Promise<T[]>{return read<T[]>(this.file)} save(rows:T[]):Promise<void>{return write(this.file,rows)}}
const productRepo=new JsonRepository<Product>(productsFile),orderRepo=new JsonRepository<Order>(ordersFile),storeRepo=new JsonRepository<Store>(storesFile);
const pgRepo=process.env.DATABASE_URL?new PostgresRepository():null;
const defaultStore:Store={id:'store-1',name:'Toshio Restaurant',tagline:'一碗热汤，一份好心情。',announcement:'欢迎光临，现已开始营业。',isOpen:true,address:'',phone:''};
if(!pgRepo){await ensure(productsFile,[]);await ensure(ordersFile,[]);await ensure(storeFile,defaultStore);try{await fs.access(storesFile)}catch{let old:Partial<Store>=defaultStore;try{old=await read<Store>(storeFile)}catch{}await write(storesFile,[{...defaultStore,...old,id:'store-1'}])}}
let stores=pgRepo?await pgRepo.stores():await storeRepo.all();if(!stores.length&&!pgRepo){stores=[defaultStore];await storeRepo.save(stores)}
const defaultId=stores[0]?.id||'store-1';
if(!pgRepo){let products=await productRepo.all(),productsChanged=false;for(const p of products){if(!p.storeId){p.storeId=defaultId;productsChanged=true}}if(productsChanged)await productRepo.save(products);let orders=await orderRepo.all(),ordersChanged=false;for(const o of orders){if(!o.storeId){o.storeId=defaultId;ordersChanged=true}}if(ordersChanged)await orderRepo.save(orders)}
function findStore(id:string){const store=stores.find(s=>s.id===id);if(!store)throw new ApiError(404,'店面不存在');return store}
function storeInput(body:any,id:string):Store{const name=String(body.name??'').trim(),tagline=String(body.tagline??'').trim(),announcement=String(body.announcement??'').trim(),address=String(body.address??'').trim(),phone=String(body.phone??'').trim();if(!name||name.length>80)throw new ApiError(400,'店名必填且不超过80字');if(tagline.length>120||announcement.length>240||address.length>160||phone.length>40)throw new ApiError(400,'店面信息长度超出限制');if(typeof body.isOpen!=='boolean')throw new ApiError(400,'营业状态无效');return{id,name,tagline,announcement,address,phone,isOpen:body.isOpen}}
function productInput(body:any):Omit<Product,'id'|'storeId'>{const name=String(body.name??'').trim(),category=String(body.category??''),price=Number(body.price),sortOrder=Number(body.sortOrder??0);if(!name||name.length>100)throw new ApiError(400,'菜品名称必填且不超过100字');if(!Number.isSafeInteger(price)||price<0)throw new ApiError(400,'价格必须为非负整数');if(!['推荐','主食','饮料','甜点'].includes(category))throw new ApiError(400,'分类无效');if(!Number.isInteger(sortOrder))throw new ApiError(400,'排序必须为整数');if(body.status!==undefined&&!['active','inactive'].includes(body.status))throw new ApiError(400,'上架状态无效');return{name,description:String(body.description??''),price,category,image:String(body.image??''),status:body.status==='inactive'?'inactive':'active',sortOrder}}
const allowedOrigins=(process.env.CORS_ORIGINS||'http://localhost:5173').split(',').map(origin=>origin.trim()).filter(Boolean);
const app=express();const production=process.env.NODE_ENV==='production';if(production){if(!process.env.ADMIN_PASSWORD_HASH||!process.env.ADMIN_JWT_SECRET)throw new Error('Production requires ADMIN_PASSWORD_HASH and ADMIN_JWT_SECRET');if(!process.env.CORS_ORIGINS||allowedOrigins.some(origin=>!origin.startsWith('https://')))throw new Error('Production CORS_ORIGINS must contain only HTTPS origins');app.set('trust proxy',1);app.use((req:Request,res:Response,next:NextFunction)=>{if(req.path.startsWith('/api/')&&!req.secure)return res.status(426).json({error:{message:'生产环境 API 仅接受 HTTPS'}});next()})}app.use(cors({origin(origin,callback){if(!origin||allowedOrigins.includes(origin))return callback(null,true);return callback(new ApiError(403,'此来源不允许访问 API'))},credentials:true}));app.use(express.json({limit:'1mb'}));if(!pgRepo)app.use('/uploads',express.static(path.join(root,'backend/uploads')));app.get('/api/health',(_q:Request,res:Response)=>res.json({data:{ok:true,database:pgRepo?'postgres':'json'}}));
const cookieName='restaurant_admin',jwtSecret=process.env.ADMIN_JWT_SECRET||'';const cookieOptions={httpOnly:true,secure:production,sameSite:(production?'none':'lax') as 'none'|'lax',path:'/' as const,maxAge:8*60*60*1000};
app.use((req:RequestWithCookies,_res:Response,next:NextFunction)=>{const raw=req.headers.cookie||'';req.cookies=Object.fromEntries(raw.split(';').map((part:string)=>part.trim().split('=')).filter((parts:string[])=>parts.length>=2).map((parts:string[])=>[parts[0],decodeURIComponent(parts.slice(1).join('='))]));next()});
app.post('/api/auth/login',rateLimit({windowMs:15*60*1000,limit:10,standardHeaders:true,legacyHeaders:false}),async(req:Request,res:Response)=>{const hash=process.env.ADMIN_PASSWORD_HASH;if(!hash||!jwtSecret)return res.status(503).json({error:{message:'管理员认证尚未初始化，请在 backend 运行 npm run setup:admin'}});const password=typeof req.body?.password==='string'?req.body.password:'';if(!password||!await bcrypt.compare(password,hash))return res.status(401).json({error:{message:'管理员密码错误'}});const token=jwt.sign({role:'admin'},jwtSecret,{subject:'admin',expiresIn:'8h'});res.cookie(cookieName,token,cookieOptions);res.json({data:{authenticated:true}})});
function requireAdmin(req:RequestWithCookies,res:Response,next:NextFunction){try{if(!jwtSecret)throw new Error('missing secret');const decoded=jwt.verify(req.cookies?.[cookieName]||'',jwtSecret) as jwt.JwtPayload;if(decoded.sub!=='admin'||decoded.role!=='admin')throw new Error('invalid session');(req as any).admin=true;next()}catch{return res.status(401).json({error:{message:'请先登录管理员账号'}})}}
app.use((req:Request,res:Response,next:NextFunction)=>{if(req.path==='/api/auth/login'||req.path==='/api/auth/logout'||req.path==='/api/health')return next();if(['POST','PUT','PATCH','DELETE'].includes(req.method)&&req.path.startsWith('/api/')){if(req.headers.origin&&!allowedOrigins.includes(req.headers.origin))return res.status(403).json({error:{message:'此来源不允许修改数据'}});if(!req.headers.origin&&String(req.headers.cookie||'').includes(`${cookieName}=`))return res.status(403).json({error:{message:'修改数据需要来自已配置的网站来源'}})}next()});
app.get('/api/auth/session',requireAdmin,(_req:Request,res:Response)=>res.json({data:{authenticated:true}}));app.post('/api/auth/logout',(_req:Request,res:Response)=>{res.clearCookie(cookieName,{httpOnly:true,secure:production,sameSite:production?'none':'lax',path:'/'});res.json({data:{loggedOut:true}})});
app.get('/api/stores',async(_q:Request,res:Response)=>res.json({data:pgRepo?await pgRepo.stores():await storeRepo.all()}));
app.post('/api/stores',requireAdmin,async(req:Request,res:Response)=>{stores=pgRepo?await pgRepo.stores():await storeRepo.all();const id=`store-${randomUUID()}`;const store=storeInput({...req.body,isOpen:req.body.isOpen??true},id);stores.push(store);if(pgRepo)await pgRepo.saveStore(store);else await storeRepo.save(stores);res.status(201).json({data:store})});
app.delete('/api/stores/:id',requireAdmin,async(req:Request,res:Response)=>{stores=pgRepo?await pgRepo.stores():await storeRepo.all();const id=String(req.params.id);if(!stores.some(s=>s.id===id))throw new ApiError(404,'店面不存在');if(stores.length<=1)throw new ApiError(409,'至少需要保留一个店铺');if(pgRepo){try{const deleted=await pgRepo.deleteStore(id);if(!deleted)throw new ApiError(404,'店面不存在')}catch(e){if(e instanceof ApiError)throw e;if((e as Error).message.includes('历史订单'))throw new ApiError(409,(e as Error).message);throw e}}else{const orders=await orderRepo.all();if(orders.some(o=>o.storeId===id))throw new ApiError(409,'该店铺存在历史订单，不能删除');const products=await productRepo.all();await productRepo.save(products.filter(p=>p.storeId!==id));stores=stores.filter(s=>s.id!==id);await storeRepo.save(stores)}stores=pgRepo?await pgRepo.stores():await storeRepo.all();res.json({data:{deleted:true}})});
app.get('/api/store',async(req:Request,res:Response)=>{stores=pgRepo?await pgRepo.stores():await storeRepo.all();const id=String(req.query.storeId||stores[0]?.id||defaultId);res.json({data:findStore(id)})});
app.put('/api/store',requireAdmin,async(req:Request,res:Response)=>{stores=pgRepo?await pgRepo.stores():await storeRepo.all();const id=String(req.query.storeId||req.body.id||stores[0]?.id||defaultId),index=stores.findIndex(s=>s.id===id);if(index<0)throw new ApiError(404,'店面不存在');stores[index]=storeInput(req.body,id);if(pgRepo)await pgRepo.saveStore(stores[index]);else await storeRepo.save(stores);res.json({data:stores[index]})});
app.get('/api/products',async(req:Request,res:Response,next:NextFunction)=>{if(req.query.includeInactive==='1')return requireAdmin(req,res,()=>sendProducts(req,res));return sendProducts(req,res)});async function sendProducts(req:Request,res:Response){const storeId=String(req.query.storeId||'');const items=pgRepo?await pgRepo.products(storeId||undefined):(await productRepo.all()).filter(p=>!storeId||p.storeId===storeId).sort((a,b)=>a.sortOrder-b.sortOrder);res.json({data:items.filter(p=>req.query.includeInactive==='1'||p.status==='active')})}
app.get('/api/products/:id',requireAdmin,async(req:Request,res:Response)=>{const id=Number(req.params.id);if(!Number.isInteger(id))throw new ApiError(400,'菜品编号无效');const p=pgRepo?await pgRepo.product(id):(await productRepo.all()).find(x=>x.id===id);if(!p)throw new ApiError(404,'菜品不存在');res.json({data:p})});
app.post('/api/products',requireAdmin,async(req:Request,res:Response)=>{const storeId=String(req.body.storeId||defaultId);findStore(storeId);const input={storeId,...productInput(req.body)},items=pgRepo?[]:await productRepo.all(),p=pgRepo?await pgRepo.createProduct(input):{id:Math.max(0,...items.map(x=>x.id))+1,...input};if(!pgRepo){items.push(p);await productRepo.save(items)}res.status(201).json({data:p})});
app.put('/api/products/:id',requireAdmin,async(req:Request,res:Response)=>{const id=Number(req.params.id);if(!Number.isInteger(id))throw new ApiError(400,'菜品编号无效');const old=pgRepo?await pgRepo.product(id):(await productRepo.all()).find(p=>p.id===id);if(!old)throw new ApiError(404,'菜品不存在');const updated={id,storeId:old.storeId,...productInput(req.body)};if(pgRepo)await pgRepo.saveProduct(updated);else{const items=await productRepo.all(),index=items.findIndex(p=>p.id===id);items[index]=updated;await productRepo.save(items)}res.json({data:updated})});
app.delete('/api/products/:id',requireAdmin,async(req:Request,res:Response)=>{const id=Number(req.params.id);if(!Number.isInteger(id))throw new ApiError(400,'菜品编号无效');if(pgRepo){if(!await pgRepo.product(id))throw new ApiError(404,'菜品不存在');await pgRepo.deleteProduct(id)}else{const items=await productRepo.all();if(!items.some(p=>p.id===id))throw new ApiError(404,'菜品不存在');await productRepo.save(items.filter(p=>p.id!==id))}res.json({data:{deleted:true}})});
const diskStorage=multer.diskStorage({destination:path.join(root,'backend/uploads'),filename:(_r,f,cb)=>cb(null,`${Date.now()}-${f.originalname.replace(/[^a-zA-Z0-9._-]/g,'_')}`)}),upload=multer({storage:pgRepo?multer.memoryStorage():diskStorage,limits:{fileSize:5*1024*1024},fileFilter:(_r,f,cb)=>['image/jpeg','image/png','image/webp'].includes(f.mimetype)?cb(null,true):cb(new ApiError(400,'仅支持 jpg、png、webp 图片'))});
app.post('/api/products/:id/image',requireAdmin,upload.single('image'),async(req:Request,res:Response)=>{const id=Number(req.params.id);if(!Number.isInteger(id))throw new ApiError(400,'菜品编号无效');if(!req.file)throw new ApiError(400,'请选择图片');if(pgRepo){const p=await pgRepo.uploadImage(id,req.file.buffer,req.file.mimetype,req.file.originalname);res.json({data:p});return}const items=await productRepo.all(),p=items.find(x=>x.id===id);if(!p)throw new ApiError(404,'菜品不存在');p.image=`/uploads/${req.file.filename}`;await productRepo.save(items);res.json({data:p})});
app.get('/api/orders',requireAdmin,async(req:Request,res:Response)=>{const storeId=String(req.query.storeId||'');res.json({data:pgRepo?await pgRepo.orders(storeId||undefined):(await orderRepo.all()).filter(o=>!storeId||o.storeId===storeId)})});
app.get('/api/orders/:id',requireAdmin,async(req:Request,res:Response)=>{const id=String(req.params.id),order=pgRepo?await pgRepo.order(id):(await orderRepo.all()).find(o=>o.id===id);if(!order)throw new ApiError(404,'订单不存在');res.json({data:order})});
app.get('/api/guest/orders/:id',async(req:Request,res:Response)=>{const token=String(req.headers['x-order-access-token']||'');let payload:jwt.JwtPayload;try{payload=jwt.verify(token,jwtSecret) as jwt.JwtPayload}catch{return res.status(401).json({error:{message:'订单访问凭证无效'}})}if(payload.scope!=='guest-order'||payload.sub!==req.params.id)return res.status(401).json({error:{message:'订单访问凭证无效'}});const order=pgRepo?await pgRepo.order(req.params.id):(await orderRepo.all()).find(o=>o.id===req.params.id);if(!order)return res.status(404).json({error:{message:'订单不存在'}});res.json({data:order})});
app.post('/api/orders',async(req:Request,res:Response)=>{if(!jwtSecret)return res.status(503).json({error:{message:'系统尚未初始化管理员会话密钥，请先设置管理员密码'}});stores=pgRepo?await pgRepo.stores():await storeRepo.all();const storeId=String(req.body.storeId||defaultId),store=findStore(storeId);if(!store.isOpen)throw new ApiError(409,'店铺当前暂停营业，暂不接单');const tableNo=String(req.body.tableNo??'').trim(),incoming=req.body.items;if(!tableNo||tableNo.length>20)throw new ApiError(400,'桌号必填且不超过20字');if(!Array.isArray(incoming)||!incoming.length)throw new ApiError(400,'订单至少包含一个商品');let order:Order;if(pgRepo)order=await pgRepo.createOrder(storeId,tableNo,incoming.map((i:any)=>({productId:Number(i.productId),quantity:Number(i.quantity)})));else{const allProducts=await productRepo.all(),items:OrderItem[]=incoming.map((item:any)=>{const p=allProducts.find(x=>x.id===Number(item.productId)&&x.storeId===storeId&&x.status==='active');if(!p)throw new ApiError(400,`商品 ${item.productId} 不存在或已下架`);const quantity=Number(item.quantity);if(!Number.isInteger(quantity)||quantity<1||quantity>99)throw new ApiError(400,'数量必须为1至99');return{productId:p.id,name:p.name,price:p.price,quantity,subtotal:p.price*quantity}});const now=new Date(),stamp=now.toISOString().slice(0,10).replaceAll('-',''),orders=await orderRepo.all(),seq=String(orders.filter(o=>o.storeId===storeId&&o.id.startsWith(`ORD-${stamp}`)).length+1).padStart(3,'0');order={id:`ORD-${stamp}-${seq}`,storeId,tableNo,items,total:items.reduce((sum,item)=>sum+item.subtotal,0),status:'new',createdAt:now.toISOString()};orders.unshift(order);await orderRepo.save(orders)}const receiptToken=jwt.sign({scope:'guest-order'},jwtSecret,{subject:order.id,expiresIn:'180d'});res.status(201).json({data:{...order,receiptToken}})});
app.patch('/api/orders/:id/status',requireAdmin,async(req:Request,res:Response)=>{if(!['new','preparing','completed','cancelled'].includes(req.body.status))throw new ApiError(400,'订单状态无效');const id=String(req.params.id);if(pgRepo){const updated=await pgRepo.setOrderStatus(id,req.body.status);if(!updated)throw new ApiError(404,'订单不存在');res.json({data:updated});return}const orders=await orderRepo.all(),order=orders.find(o=>o.id===id);if(!order)throw new ApiError(404,'订单不存在');order.status=req.body.status;await orderRepo.save(orders);res.json({data:order})});
app.use((err:unknown,_req:Request,res:Response,_next:NextFunction)=>{const error=err as any,status=error instanceof ApiError?error.status:error instanceof multer.MulterError?(error.code==='LIMIT_FILE_SIZE'?413:400):500;res.status(status).json({error:{message:error instanceof ApiError?error.message:error instanceof multer.MulterError?(error.code==='LIMIT_FILE_SIZE'?'图片不能超过5MB':'图片上传失败'):'服务器内部错误'}})});
const port=Number(process.env.PORT)||3000;app.listen(port,()=>console.log(`API ready at http://localhost:${port}`));

