import { Pool, PoolClient } from 'pg';
import { createSupabaseClient } from './supabase-client.js';

export type Store={id:string;name:string;tagline:string;announcement:string;isOpen:boolean;address:string;phone:string};
export type Product={id:number;storeId:string;name:string;description:string;price:number;category:string;image:string;status:'active'|'inactive';sortOrder:number};
export type OrderItem={productId:number;name:string;price:number;quantity:number;subtotal:number};
export type Order={id:string;storeId:string;tableNo:string;items:OrderItem[];total:number;status:'new'|'preparing'|'completed'|'cancelled';createdAt:string};

type OrderRecordRow={id:string;store_id:string;table_no:string;total:number;status:Order['status'];created_at:Date|string};
type OrderItemRecordRow={order_id:string;product_id:number|string|null;product_name:string;unit_price:number;quantity:number;subtotal:number};
type ActiveProductRow={id:number|string;name:string;price:number};

export class PostgresRepository {
 private pool:Pool;
 private storage;
 constructor(){if(!process.env.DATABASE_URL)throw new Error('DATABASE_URL is required in PostgreSQL mode');this.pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.PGSSLMODE==='disable'?false:{rejectUnauthorized:false}});const key=process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY;if(!process.env.SUPABASE_URL||!key)throw new Error('SUPABASE_URL and SUPABASE_SECRET_KEY are required in PostgreSQL mode');this.storage=createSupabaseClient(process.env.SUPABASE_URL,key).storage}
 async stores():Promise<Store[]>{const {rows}=await this.pool.query('select id,name,tagline,announcement,is_open,address,phone from stores order by created_at,id');return rows.map(r=>({id:r.id,name:r.name,tagline:r.tagline,announcement:r.announcement,isOpen:r.is_open,address:r.address,phone:r.phone}))}
 async store(id:string):Promise<Store|undefined>{return (await this.stores()).find(s=>s.id===id)}
 async saveStore(s:Store){await this.pool.query(`insert into stores(id,name,tagline,announcement,is_open,address,phone) values($1,$2,$3,$4,$5,$6,$7) on conflict(id) do update set name=excluded.name,tagline=excluded.tagline,announcement=excluded.announcement,is_open=excluded.is_open,address=excluded.address,phone=excluded.phone`,[s.id,s.name,s.tagline,s.announcement,s.isOpen,s.address,s.phone])}
 async deleteStore(id:string){const c=await this.pool.connect();try{await c.query('begin');const orders=await c.query('select 1 from orders where store_id=$1 limit 1',[id]);if(orders.rowCount)throw new Error('该店铺存在历史订单，不能删除');await c.query('delete from products where store_id=$1',[id]);const result=await c.query('delete from stores where id=$1',[id]);await c.query('commit');return Boolean(result.rowCount)}catch(e){await c.query('rollback');throw e}finally{c.release()}}
 async products(storeId?:string):Promise<Product[]>{const {rows}=await this.pool.query(`select p.id,p.store_id,p.name,p.description,p.price,c.name category,p.image,p.status,p.sort_order from products p join categories c on c.id=p.category_id ${storeId?'where p.store_id=$1':''} order by p.sort_order,p.id`,storeId?[storeId]:[]);return rows.map(r=>({id:Number(r.id),storeId:r.store_id,name:r.name,description:r.description,price:r.price,category:r.category,image:r.image,status:r.status,sortOrder:r.sort_order}))}
 async product(id:number):Promise<Product|undefined>{return (await this.products()).find(p=>p.id===id)}
 async createProduct(p:Omit<Product,'id'>):Promise<Product>{const c=await this.pool.connect();try{await c.query('begin');const cat=await c.query(`insert into categories(store_id,name,sort_order) values($1,$2,0) on conflict(store_id,name) do update set name=excluded.name returning id`,[p.storeId,p.category]);const r=await c.query(`insert into products(store_id,name,description,price,category_id,image,status,sort_order) values($1,$2,$3,$4,$5,$6,$7,$8) returning id`,[p.storeId,p.name,p.description,p.price,cat.rows[0].id,p.image,p.status,p.sortOrder]);await c.query('commit');return{id:Number(r.rows[0].id),...p}}catch(e){await c.query('rollback');throw e}finally{c.release()}}
 async saveProduct(p:Product){const c=await this.pool.connect();try{await c.query('begin');const {rows}=await c.query(`insert into categories(store_id,name,sort_order) values($1,$2,0) on conflict(store_id,name) do update set name=excluded.name returning id`,[p.storeId,p.category]);await c.query(`insert into products(id,store_id,name,description,price,category_id,image,status,sort_order) values($1,$2,$3,$4,$5,$6,$7,$8,$9) on conflict(id) do update set store_id=excluded.store_id,name=excluded.name,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,status=excluded.status,sort_order=excluded.sort_order`,[p.id,p.storeId,p.name,p.description,p.price,rows[0].id,p.image,p.status,p.sortOrder]);await c.query(`select setval(pg_get_serial_sequence('products','id'),greatest(coalesce((select max(id) from products),1),$1),true)`,[p.id]);await c.query('commit')}catch(e){await c.query('rollback');throw e}finally{c.release()}}
 async deleteProduct(id:number){await this.pool.query('delete from products where id=$1',[id])}
 async uploadImage(productId:number,buffer:Buffer,mime:string,originalName:string){const p=await this.product(productId);if(!p)throw new Error('菜品不存在');const ext=mime==='image/jpeg'?'jpg':mime==='image/png'?'png':'webp',key=`${p.storeId}/${productId}-${Date.now()}.${ext}`;const {error}=await this.storage.from('product-images').upload(key,buffer,{contentType:mime,upsert:true});if(error)throw error;const url=this.storage.from('product-images').getPublicUrl(key).data.publicUrl;p.image=url;await this.saveProduct(p);return p}
 async orders(storeId?:string):Promise<Order[]>{const {rows}=await this.pool.query<OrderRecordRow>(`select id,store_id,table_no,total,status,created_at from orders ${storeId?'where store_id=$1':''} order by created_at desc`,storeId?[storeId]:[]);if(!rows.length)return[];const ids=rows.map((r:OrderRecordRow)=>r.id),items=await this.pool.query<OrderItemRecordRow>('select order_id,product_id,product_name,unit_price,quantity,subtotal from order_items where order_id=any($1::text[]) order by id',[ids]);const group=new Map<string,OrderItem[]>();for(const i of items.rows){const list=group.get(i.order_id)||[];list.push({productId:Number(i.product_id),name:i.product_name,price:i.unit_price,quantity:i.quantity,subtotal:i.subtotal});group.set(i.order_id,list)}return rows.map((r:OrderRecordRow)=>({id:r.id,storeId:r.store_id,tableNo:r.table_no,total:r.total,status:r.status,createdAt:new Date(r.created_at).toISOString(),items:group.get(r.id)||[]}))}
 async order(id:string){return (await this.orders()).find(o=>o.id===id)}
 async createOrder(storeId:string,tableNo:string,incoming:Array<{productId:number;quantity:number}>):Promise<Order>{const c=await this.pool.connect();try{await c.query('begin');const store=await c.query<{is_open:boolean}>('select is_open from stores where id=$1 for share',[storeId]);if(!store.rowCount)throw new Error('店面不存在');if(!store.rows[0].is_open)throw new Error('店铺当前暂停营业，暂不接单');const ids=[...new Set(incoming.map(i=>i.productId))],found=await c.query<ActiveProductRow>(`select id,name,price from products where store_id=$1 and status='active' and id=any($2::bigint[]) for share`,[storeId,ids]);if(found.rows.length!==ids.length)throw new Error('订单包含不存在或已下架的商品');const items=incoming.map(i=>{if(!Number.isInteger(i.quantity)||i.quantity<1||i.quantity>99)throw new Error('数量必须为1至99');const p=found.rows.find((x:ActiveProductRow)=>Number(x.id)===i.productId)!;return{productId:i.productId,name:p.name,price:p.price,quantity:i.quantity,subtotal:p.price*i.quantity}});const now=new Date(),stamp=now.toISOString().slice(0,10).replaceAll('-',''),prefix=`ORD-${stamp}-`;await c.query('select pg_advisory_xact_lock(hashtext($1))',[`${storeId}:${stamp}`]);const count=await c.query('select count(*)::int n from orders where store_id=$1 and id like $2',[storeId,`${prefix}%`]),id=`${prefix}${String(count.rows[0].n+1).padStart(3,'0')}`,total=items.reduce((s,i)=>s+i.subtotal,0);await c.query('insert into orders(id,store_id,table_no,total,status,created_at) values($1,$2,$3,$4,$5,$6)',[id,storeId,tableNo,total,'new',now.toISOString()]);for(const i of items)await c.query('insert into order_items(order_id,product_id,product_name,unit_price,quantity,subtotal) values($1,$2,$3,$4,$5,$6)',[id,i.productId,i.name,i.price,i.quantity,i.subtotal]);await c.query('commit');return{id,storeId,tableNo,items,total,status:'new',createdAt:now.toISOString()}}catch(e){await c.query('rollback');throw e}finally{c.release()}}
 async setOrderStatus(id:string,status:Order['status']){const r=await this.pool.query('update orders set status=$2 where id=$1 returning id',[id,status]);if(!r.rowCount)return undefined;return this.order(id)}
 async close(){await this.pool.end()}
}
